name: flutter_api_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  catppuccin_flutter: ^1.0.0
  lucide_icons_flutter: ^3.1.0
  shared_preferences: ^2.5.3
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/meow_code.gif
      - assets/meow_nod.gif